{% set name = "mysql-connector-python" %}
{% set version = "2.2.2" %}
{% set sha256 = "fe46832fa4007c81c5aff6574f2852f301f105bf1e351d5cc69e012309116fa1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/mysql/mysql-connector-python/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}
  patches:
    - setup.py.patch # ensure it is installed as mysql-connector instead of mysql-connector-python...

build:
  number: 1
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv "

requirements:
  build:
    - python
  run:
    - python

test:
  imports:
    - mysql.connector

about:
  home: https://dev.mysql.com/doc/connector-python/en/
  license: GPL-2.0
  license_family: GPL
  license_file: LICENSE.txt
  summary: 'Python driver for communicating with MySQL servers'

  description: |
    MySQL Connector/Python is a standardized database driver for Python
    platforms and development.  
  doc_url: http://dev.mysql.com/doc/connector-python/en/index.html
  dev_url: https://github.com/mysql/mysql-connector-python

extra:
  recipe-maintainers:
    - synapticarbors
