{% set name = "stomp.py" %}
{% set version = "4.1.21" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 0b06828a281ebf288f0b0b4152d29c73d440408161e0265b677e6382ad3aa9e3

build:
  number: 0
  entry_points:
    - stomp = stomp.__main__:main
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv "

requirements:
  host:
    - docopt >=0.6.2
    - pip
    - python
  run:
    - docopt >=0.6.2
    - python

test:
  imports:
    - stomp
    - stomp.adapter
  commands:
    - stomp --help

about:
  home: https://github.com/jasonrbriggs/stomp.py
  license: Apache Software
  license_family: APACHE
  license_file: 
  summary: Python STOMP client, supporting versions 1.0, 1.1 and 1.2 of the protocol
  doc_url: 
  dev_url: 

extra:
  recipe-maintainers:
    - your-github-id-here
