{% set name = "python-icat" %}
{% set version = "0.14.2" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://github.com/icatproject/{{ name }}/archive/rel-{{ version }}.tar.gz
  sha256: 70cb6f9031cdc487a57929c1c42d7b06f04c6fdc1f5f27ee03770345982ff2b1

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv "
  noarch: python

requirements:
  host:
    - pip
    - python
  run:
    - python
    - suds-jurko

test:
  imports:
    - icat

about:
        home: https://github.com/icatproject/python-icat

extra:
  recipe-maintainers:
    - your-github-id-here
