{% set name = "wrapspawner" %}
{% set version = "2019.06.17" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  git_url: https://github.com/jupyterhub/wrapspawner.git
  git_rev: master

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vvv "
  noarch: python

requirements:
  host:
    - pip
    - python
    - setuptools
  run:
    - python
    - tornado
    - jupyterhub
    - traitlets

test:
  imports:
    - wrapspawner

about:
  home: https://github.com/jupyterhub/wrapspawner
  license: BSD-3
  license_file: LICENSE
  summary: Mechanism for runtime configuration of spawners for JupyterHub

extra:
  recipe-maintainers:
    - tschoonj
