# executed as
# singularity exec -B /scratch,/dls_sw/apps /scratch/singularity/images/rhel6-dev.simg /dls_sw/apps/python/anaconda/4.6.14/64/bin/conda build --python 3.7 .

{% set name = "SRW" %}
{% set version = "2019.08.04" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  git_url: https://github.com/ochubar/SRW.git
  git_rev: 5d3d4cff1e64f6c6587a5731fb94efdb4612c06e
  patches:
    - mypatch.diff

build:
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - git
  host:
    - git
    - make
    - python
    - fftw
  run:
    - python
    - fftw
    - numpy
    - matplotlib
    - pillow

test:
  imports:
    - srwlib

