{% set name = "relion_yolo_it" %}
{% set version = "0.2.2" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
        url: file:///dls_sw/apps/EM/relion_cryolo/live/Cryolo_relion3.0/dist/relion_yolo_it-{{ version }}.tar.gz

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv "
  noarch: python

requirements:
  host:
    - pip
    - python ==3.6.8
    - setuptools
  run:
    - python ==3.6.8
    - setuptools
    - gemmi ==0.2.8
    - numpy ==1.14.5

test:
  imports:
    - relion_yolo_it

about:
  license: BSD
  license_family: BSD
  license_file: 
  summary: Updated relion_it with cryolo wrappers for Diamond Light Source
  doc_url: 
  dev_url: 

extra:
  recipe-maintainers:
    - tschoonj
